# Generated by Django 3.2.12 on 2022-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('video', models.URLField(blank=True, null=True, verbose_name='video')),
                ('titile', models.CharField(max_length=255)),
                ('body', models.TextField(verbose_name='blog matni')),
                ('aforizm', models.TextField(blank=True, null=True, verbose_name='aqilli gaplar')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='aforizm egasi')),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
