# Generated by Django 3.2.12 on 2022-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile'),
        ),
    ]
