# Generated by Django 3.2.12 on 2022-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aforizm_egasi',
            new_name='name_aforiz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='aforizm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='aqilli gaplar'),
        ),
    ]
