# Generated by Django 3.2.12 on 2022-08-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220825_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='video_img'),
        ),
    ]
