# Generated by Django 3.2.12 on 2022-09-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image_qoshimcha'),
        ),
    ]
