# Generated by Django 3.2.12 on 2022-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='aforizm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name_aforiz',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
