# Generated by Django 3.2.12 on 2022-09-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220906_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
    ]
