# Generated by Django 3.2.12 on 2022-09-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='CommentsBlog',
        ),
    ]
