# Generated by Django 3.2.12 on 2022-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, default='banner_1.jpg', upload_to='', verbose_name='450x200'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='mahsulotning nomi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='price',
            field=models.FloatField(verbose_name='mahsulotning narxi'),
        ),
    ]
