# Generated by Django 3.2.12 on 2022-09-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerLefts',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='FeatureLeft',
        ),
        migrations.DeleteModel(
            name='FeatureRights',
        ),
    ]
