# Generated by Django 3.2.12 on 2022-08-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_auto_20220821_0602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Products',
        ),
    ]
