# Generated by Django 3.2.12 on 2022-09-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_auto_20220920_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.IntegerField(blank=True, null=True, verbose_name='mahsulotning eski narxi'),
        ),
    ]
