# Generated by Django 3.2.12 on 2022-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_alter_products_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='brend'),
        ),
    ]
