# Generated by Django 3.2.12 on 2022-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(verbose_name='mahsulotning narxi')),
            ],
        ),
    ]
