# Generated by Django 3.2.12 on 2022-08-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='nomer',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='getinfo',
            name='email',
        ),
    ]
