# Generated by Django 3.2.12 on 2022-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_products_brend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
