# Generated by Django 3.2.12 on 2022-08-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_bannerleft'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='BannerRight',
        ),
    ]
