# Generated by Django 4.1.1 on 2022-09-27 18:46

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_reklamaview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklamaview',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='reklamaview',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
