# Generated by Django 3.2.12 on 2022-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_rename_products_bannerright'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_old', models.FloatField(blank=True, null=True, verbose_name='mahsulotning eski narxi')),
                ('price_new', models.FloatField(verbose_name='mahsulotning yangi narxi')),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'NEW'), ('sale', 'SALE')], max_length=200, null=True)),
            ],
        ),
    ]
