# Generated by Django 3.2.12 on 2022-08-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0008_auto_20220830_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='product',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='subcomments',
            old_name='product',
            new_name='prod',
        ),
    ]
