# Generated by Django 3.2.12 on 2022-08-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0009_categories_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerLeft',
        ),
        migrations.DeleteModel(
            name='BannerRight',
        ),
        migrations.DeleteModel(
            name='DayOffer',
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'NEW'), ('sale', 'SALE')], max_length=50, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='mahsulot haqida qisqacha'),
        ),
    ]
