# Generated by Django 3.2.12 on 2022-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0009_auto_20220830_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
