# Generated by Django 3.2.12 on 2022-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0010_auto_20220822_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='price_new',
            field=models.FloatField(default=15, verbose_name='mahsulotning yangi narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price_old',
            field=models.FloatField(default=1, verbose_name='mahsulotning eski narxi'),
            preserve_default=False,
        ),
    ]
