# Generated by Django 3.2.12 on 2022-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0011_auto_20220822_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
    ]
