# Generated by Django 3.2.12 on 2022-08-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0011_auto_20220830_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='mes',
        ),
    ]
