# Generated by Django 3.2.12 on 2022-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0012_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.CharField(blank=True, max_length=100, verbose_name='mahsulotning eski narxi'),
        ),
    ]
