# Generated by Django 3.2.12 on 2022-08-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_auto_20220830_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='products',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='subcomments',
            old_name='products',
            new_name='items',
        ),
    ]
