# Generated by Django 3.2.12 on 2022-08-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_auto_20220822_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerLeft',
            new_name='BannerLefts',
        ),
    ]
