# Generated by Django 3.2.12 on 2022-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_bannerleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.CharField(blank=True, max_length=100, verbose_name='mahsulotning eski narxi'),
        ),
    ]
