# Generated by Django 3.2.12 on 2022-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0014_rename_bannerleft_bannerlefts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='mahsulotning eski narxi'),
        ),
    ]
