# Generated by Django 3.2.12 on 2022-08-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0014_auto_20220830_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='mes',
            new_name='body',
        ),
    ]
