# Generated by Django 3.2.12 on 2022-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0015_rename_mes_comments_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='body',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
