# Generated by Django 3.2.12 on 2022-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0015_auto_20220823_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_old', models.FloatField(verbose_name='mahsulotning eski narxi')),
                ('price_new', models.FloatField(verbose_name='mahsulotning yangi narxi')),
                ('predecessor', models.CharField(default=None, max_length=255)),
                ('supporttype', models.CharField(default=None, max_length=255)),
                ('cushioning', models.CharField(default=None, max_length=255)),
                ('totalweight', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
