# Generated by Django 3.2.12 on 2022-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0016_featurerights'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerights',
            name='image',
            field=models.ImageField(default=4, upload_to=''),
            preserve_default=False,
        ),
    ]
