# Generated by Django 3.2.12 on 2022-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0016_auto_20220830_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubComments',
        ),
    ]
