# Generated by Django 3.2.12 on 2022-08-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0018_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
    ]
