# Generated by Django 3.2.12 on 2022-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0019_auto_20220831_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
