# Generated by Django 3.2.12 on 2022-08-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0020_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='flightapp.products'),
        ),
    ]
