# Generated by Django 3.2.12 on 2022-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0020_cart_customermodel_orderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
