# Generated by Django 3.2.12 on 2022-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0021_getinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinfo',
            name='nomer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
