# Generated by Django 3.2.12 on 2022-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0022_getinfo_nomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfo',
            name='nomer',
            field=models.PositiveBigIntegerField(),
        ),
    ]
