# Generated by Django 3.2.12 on 2022-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0023_alter_getinfo_nomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='materials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='materials'),
        ),
        migrations.AddField(
            model_name='products',
            name='olchami',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='olchami'),
        ),
        migrations.AddField(
            model_name='products',
            name='other_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='weight'),
        ),
    ]
