name: ParvozTrade CD

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: flight.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

          TELEBOT_URL: ${{ secrets.TELEBOT_URL }}
          TELEBOT_TOKEN: ${{ secrets.TELEBOT_TOKEN }}
          TELEBOT_CHAT_ID_ZAKAS: ${{ secrets.TELEBOT_CHAT_ID_ZAKAS }}
          TELEBOT_CHAT_ID_SAVOL: ${{ secrets.TELEBOT_CHAT_ID_SAVOL }}

          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

          POSTGRES_ENGINE: django.db.backends.postgresql
          POSTGRES_DB: testr
          POSTGRES_USER: testr
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: python3 manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ParvozTrade
          git pull origin main
          python3 manage.py migrate
          python3 manage.py collectstatic
          cp -r /root/ParvozTrade/static /var/www/static/
          cp -r /root/ParvozTrade/media /var/www/media/
          systemctl restart gunicorn.service
      
      