name: ParvozTrade CI


on: [push]
    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: flight.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

          TELEBOT_URL: ${{ env.TELEBOT_URL }}
          TELEBOT_TOKEN: ${{ env.TELEBOT_TOKEN }}
          TELEBOT_CHAT_ID_ZAKAS: ${{ env.TELEBOT_CHAT_ID_ZAKAS }}
          TELEBOT_CHAT_ID_SAVOL: ${{ env.TELEBOT_CHAT_ID_SAVOL }}

          EMAIL_HOST: ${{ env.EMAIL_HOST }}
          EMAIL_PORT: ${{ env.EMAIL_PORT }}
          EMAIL_USE_TLS: ${{ env.EMAIL_USE_TLS }}
          EMAIL_HOST_USER: ${{ env.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ env.EMAIL_HOST_PASSWORD }}

          POSTGRES_ENGINE: django.db.backends.postgresql
          POSTGRES_DB: testr
          POSTGRES_USER: testr
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: python3 manage.py test
